import type { IDataValidationRule, IWorkbookData } from '@univerjs/core'
import { DataValidationErrorStyle, DataValidationOperator, DataValidationType } from '@univerjs/core'
import { LocaleType } from '@univerjs/presets'
import { DATA_VALIDATION_PLUGIN_NAME } from '@univerjs/sheets-data-validation'

/**
 * Below is cells`s data validators.
 */
const dataValidation: IDataValidationRule[] = [
  {
    uid: 'validator-1',
    type: DataValidationType.DECIMAL,
    ranges: [{
      startRow: 2,
      endRow: 5,
      startColumn: 0,
      endColumn: 3,
    }],
    operator: DataValidationOperator.GREATER_THAN,
    formula1: '111',
    errorStyle: DataValidationErrorStyle.STOP,
  },
]

/**
 * Below is the initial data for cells in the Sheet1.
 */
export const DEFAULT_WORKBOOK_DATA_DEMO: IWorkbookData = {
  id: 'Sheet1',
  locale: LocaleType.ZH_CN,
  name: 'Panda Sheet',
  appVersion: 'panda-0.8.1',
  sheetOrder: ['Sheet1'],
  styles: {
    1: {
      vt: 2,
      ht: 2,
      bl: 1,
      bg: {
        rgb: 'rgb(255,226,102)',
      },
      pd: {
        l: 5,
      },
      bd: {
        t: {
          s: 8,
          cl: {
            rgb: 'rgb(217,217,217)',
          },
        },
        l: {
          s: 8,
          cl: {
            rgb: 'rgb(217,217,217)',
          },
        },
        r: {
          s: 8,
          cl: {
            rgb: 'rgb(217,217,217)',
          },
        },
        b: {
          s: 8,
          cl: {
            rgb: 'rgb(217,217,217)',
          },
        },
      },
    },
  },
  sheets: {
    Sheet1: {
      name: 'Sheet1',
      id: 'Sheet1',
      tabColor: '',
      hidden: 0,
      rowCount: 1000,
      columnCount: 94,
      defaultColumnWidth: 100,
      defaultRowHeight: 25,
      /**
           freeze: {
          xSplit: 9,
          ySplit: 2,
          startRow: 0,
          startColumn: 9,
      },
       */
      cellData: {
        0: {
          0: { s: '1', v: '职能中心' },
          1: { s: '1', v: 'KPI绩效指标' },
          2: { s: '1', v: '考核权重' },
          3: { s: '1', v: '被考核单元' },
          4: { s: '1', v: '被考核部门' },
          5: { s: '1', v: '考核年度' },
          6: { s: '1', v: '考核周期' },
          7: { s: '1', v: '最低目标值' },
          8: { s: '1', v: '考核目标值' },
          9: { s: '1', v: '挑战目标值' },
          10: { s: '1', v: '一月' },
          17: { s: '1', v: '二月' },
          24: { s: '1', v: '三月' },
          31: { s: '1', v: '四月' },
          38: { s: '1', v: '五月' },
          45: { s: '1', v: '六月' },
          52: { s: '1', v: '七月' },
          59: { s: '1', v: '八月' },
          66: { s: '1', v: '九月' },
          73: { s: '1', v: '十月' },
          80: { s: '1', v: '十一月' },
          87: { s: '1', v: '十二月' },
        },
        1: {
          0: { s: '1', v: '' },
          1: { s: '1', v: '' },
          2: { s: '1', v: '' },
          3: { s: '1', v: '' },
          4: { s: '1', v: '' },
          5: { s: '1', v: '' },
          6: { s: '1', v: '' },
          7: { s: '1', v: '' },
          8: { s: '1', v: '' },
          9: { s: '1', v: '' },
          10: { s: '1', v: '实际值' },
          11: { s: '1', v: '去年同期' },
          12: { s: '1', v: '得分' },
          13: { s: '1', v: '达标情况' },
          14: { s: '1', v: '原因分析' },
          15: { s: '1', v: '纠正措施' },
          16: { s: '1', v: '完成时间' },
          17: { s: '1', v: '实际值' },
          18: { s: '1', v: '去年同期' },
          19: { s: '1', v: '得分' },
          20: { s: '1', v: '达标情况' },
          21: { s: '1', v: '原因分析' },
          22: { s: '1', v: '纠正措施' },
          23: { s: '1', v: '完成时间' },
          24: { s: '1', v: '实际值' },
          25: { s: '1', v: '去年同期' },
          26: { s: '1', v: '得分' },
          27: { s: '1', v: '达标情况' },
          28: { s: '1', v: '原因分析' },
          29: { s: '1', v: '纠正措施' },
          30: { s: '1', v: '完成时间' },
          31: { s: '1', v: '实际值' },
          32: { s: '1', v: '去年同期' },
          33: { s: '1', v: '得分' },
          34: { s: '1', v: '达标情况' },
          35: { s: '1', v: '原因分析' },
          36: { s: '1', v: '纠正措施' },
          37: { s: '1', v: '完成时间' },
          38: { s: '1', v: '实际值' },
          39: { s: '1', v: '去年同期' },
          40: { s: '1', v: '得分' },
          41: { s: '1', v: '达标情况' },
          42: { s: '1', v: '原因分析' },
          43: { s: '1', v: '纠正措施' },
          44: { s: '1', v: '完成时间' },
          45: { s: '1', v: '实际值' },
          46: { s: '1', v: '去年同期' },
          47: { s: '1', v: '得分' },
          48: { s: '1', v: '达标情况' },
          49: { s: '1', v: '原因分析' },
          50: { s: '1', v: '纠正措施' },
          51: { s: '1', v: '完成时间' },
          52: { s: '1', v: '实际值' },
          53: { s: '1', v: '去年同期' },
          54: { s: '1', v: '得分' },
          55: { s: '1', v: '达标情况' },
          56: { s: '1', v: '原因分析' },
          57: { s: '1', v: '纠正措施' },
          58: { s: '1', v: '完成时间' },
          59: { s: '1', v: '实际值' },
          60: { s: '1', v: '去年同期' },
          61: { s: '1', v: '得分' },
          62: { s: '1', v: '达标情况' },
          63: { s: '1', v: '原因分析' },
          64: { s: '1', v: '纠正措施' },
          65: { s: '1', v: '完成时间' },
          66: { s: '1', v: '实际值' },
          67: { s: '1', v: '去年同期' },
          68: { s: '1', v: '得分' },
          69: { s: '1', v: '达标情况' },
          70: { s: '1', v: '原因分析' },
          71: { s: '1', v: '纠正措施' },
          72: { s: '1', v: '完成时间' },
          73: { s: '1', v: '实际值' },
          74: { s: '1', v: '去年同期' },
          75: { s: '1', v: '得分' },
          76: { s: '1', v: '达标情况' },
          77: { s: '1', v: '原因分析' },
          78: { s: '1', v: '纠正措施' },
          79: { s: '1', v: '完成时间' },
          80: { s: '1', v: '实际值' },
          81: { s: '1', v: '去年同期' },
          82: { s: '1', v: '得分' },
          83: { s: '1', v: '达标情况' },
          84: { s: '1', v: '原因分析' },
          85: { s: '1', v: '纠正措施' },
          86: { s: '1', v: '完成时间' },
          87: { s: '1', v: '实际值' },
          88: { s: '1', v: '去年同期' },
          89: { s: '1', v: '得分' },
          90: { s: '1', v: '达标情况' },
          91: { s: '1', v: '原因分析' },
          92: { s: '1', v: '纠正措施' },
          93: { s: '1', v: '完成时间' },
        },
      },
      mergeData: [
        { startRow: 0, endRow: 1, startColumn: 0, endColumn: 0 },
        { startRow: 0, endRow: 1, startColumn: 1, endColumn: 1 },
        { startRow: 0, endRow: 1, startColumn: 2, endColumn: 2 },
        { startRow: 0, endRow: 1, startColumn: 3, endColumn: 3 },
        { startRow: 0, endRow: 1, startColumn: 4, endColumn: 4 },
        { startRow: 0, endRow: 1, startColumn: 5, endColumn: 5 },
        { startRow: 0, endRow: 1, startColumn: 6, endColumn: 6 },
        { startRow: 0, endRow: 1, startColumn: 7, endColumn: 7 },
        { startRow: 0, endRow: 1, startColumn: 8, endColumn: 8 },
        { startRow: 0, endRow: 1, startColumn: 9, endColumn: 9 },
        { startRow: 0, endRow: 0, startColumn: 10, endColumn: 16 },
        { startRow: 0, endRow: 0, startColumn: 17, endColumn: 23 },
        { startRow: 0, endRow: 0, startColumn: 24, endColumn: 30 },
        { startRow: 0, endRow: 0, startColumn: 31, endColumn: 37 },
        { startRow: 0, endRow: 0, startColumn: 38, endColumn: 44 },
        { startRow: 0, endRow: 0, startColumn: 45, endColumn: 51 },
        { startRow: 0, endRow: 0, startColumn: 52, endColumn: 58 },
        { startRow: 0, endRow: 0, startColumn: 59, endColumn: 65 },
        { startRow: 0, endRow: 0, startColumn: 66, endColumn: 72 },
        { startRow: 0, endRow: 0, startColumn: 73, endColumn: 79 },
        { startRow: 0, endRow: 0, startColumn: 80, endColumn: 86 },
        { startRow: 0, endRow: 0, startColumn: 87, endColumn: 93 },
      ],
      rowData: {

      },
      scrollTop: 0,
      scrollLeft: 0,
      showGridlines: 1,
      // gridlinesColor: 'rgb(9, 30, 250)',
      rowHeader: {
        width: 46,
        hidden: 0,
      },
      columnHeader: {
        height: 20,
        hidden: 0,
      },
    },
  },
  resources: [
    {
      name: DATA_VALIDATION_PLUGIN_NAME,
      data: JSON.stringify({
        Sheet1: dataValidation,
      }),
    },
  ],
}
